Add expected min/max Double variants for compatibility
For libraries using Micrometer that compile against 1.5.x but support 1.3.x at runtime, these missing methods caused NoSuchMethodErrors. This adds these so at least the next patch version of 1.3.x can be supported.

Resolves #2123